### ISSUE TITLE
insightful package, but do you have any comparison with Latent Gold ?

### ISSUE THREAD

**Issue by peter159** [Labo-Lacourse/stepmix#30]
Hi, this is a insightful package, do you have any info about comparing your package result with Latent gold software ?

**Comment by MostafaAbdelrashied** [comment]
Hey Peter!

Previously, I did a comparison study using different classification datasets on both tools. The good news is, the results were pretty similar across four datasets. To make it easier for you, I've put together a brief PowerPoint presentation summarizing my findings. You can find it attached.
[comparison.pptx](https://github.com/Labo-Lacourse/stepmix/files/11582239/comparison.pptx)

**Comment by sachaMorin** [comment]
We did a simulation comparison of StepMix and Latent Gold in our [preprint](https://arxiv.org/pdf/2304.03853.pdf) for parameter point estimates. Compare table 3 and 4 for example. Both tools yield very similar results.

**Comment by peter159** [comment]
I'd like to also understand, what if I have continuous, categorical, and binary data with missing values, how do I express a model with response variable and covarites using stepmix package ? for e.g. estimating a latent class regression ?

**Comment by peter159** [comment]
> We definitely need a better example of a complete model with all these options. In the meantime, I posted an example in issue #35 .

thanks，I'll take some test it with real data，in any case it means this package is flexible expressing different model forms
