### ISSUE TITLE
Calculation of the number of parameters in continuous LCA

### ISSUE THREAD

**Issue by justinsavoie** [Labo-Lacourse/stepmix#40]
Hello, and thanks for this great package! 

In the first example of the first tutorial (LCA with Continuous Features) the number of estimated parameters is 28. Is there a reason for this? Normally for a diagonal GMM like this one it would be 12 (means) + 12 (variances) + 2 (number of weights - 1) = 26? That seems to be what is calculated in e.g. mclust or sklearn.mixture.GaussianMixture. It's also possible I misunderstand and there is no issue.

**Comment by sachaMorin** [comment]
You are correct. I can reproduce. Thanks for reporting

**Comment by sachaMorin** [comment]
I think I found the problem.  For counting parameters, StepMix simply adds the number of parameters in the measurement and structural models to n_components - 1 in the main class (i.e., the class weights).

For Gaussian measurement models however, StepMix actually relies on the sklearn Gaussian mixture class, which already includes the class weights. Class weights are therefore included twice.

**Comment by sachaMorin** [comment]
This should be fixed with [the changes in 1.2.3 and 1.2.4.](https://github.com/Labo-Lacourse/stepmix/releases) Thanks again,
