### ISSUE TITLE
Sample method

### ISSUE THREAD

**Issue by pcomw** [Labo-Lacourse/stepmix#45]
First, thank you for the wonderful package. Second, apologies if this is a foolish issue to raise.

I'm having difficulty implementing the sample() method. For example, when I run the code in the first tutorial, and attempt to run `model.sample(10)`, I receive the error "TypeError: 'NoneType' object is not subscriptable", pointing to line 1326 of stepmix.py `Y[shuffle_mask]`. 

If I'm using the method incorrectly, then I would be grateful if its proper use could be documented in a tutorial. Thanks!

**Comment by sachaMorin** [comment]
Hey thanks for reporting this! Definitely a bug when trying to sample a model with no structural model (i.e., no Y). Will fix
