### ISSUE TITLE
is there any solution when there are many observations per respondent

### ISSUE THREAD

**Issue by peter159** [Labo-Lacourse/stepmix#49]
like the question titled, and when I want to segment respondent applying this stepmix package

**Comment by peter159** [comment]
thank you

**Comment by sachaMorin** [comment]
@ericlacourse pointed out that you could consider [RMLCA](https://ctri.wisc.edu/researchers/behavior-change-analysis/rmlca/) which can be achieved (I think) with StepMix. You would need to structure your n respondents with k repeated measurements as an n x k data frame and use this as input to StepMix.

**Comment by sachaMorin** [comment]
Closing. Feel free to reopen if needed.
