### ISSUE TITLE
Question about Sample Weighting in StepMix

### ISSUE THREAD

**Issue by FelixLaliberte** [Labo-Lacourse/stepmix#51]
Hello,

Does StepMix allow for sample weighting? If so, would it be possible to know how?

Thank you,

**Comment by sachaMorin** [comment]
Various StepMix methods accept a `sample_weight` argument. Here's [the documentation](https://stepmix.readthedocs.io/en/latest/api.html#stepmix.stepmix.StepMix.fit) for the `fit` method.

**Comment by FelixLaliberte** [comment]
Great! Thanks for this response.
