### ISSUE TITLE
Covariate, Distal Outcomes, and Indicators

### ISSUE THREAD

**Issue by yuanjames** [Labo-Lacourse/stepmix#52]
Hi,

Thank you for your work in building such a great Python repository!

I have recently used this repository; however, I am a bit confused regarding the three input data types.

I believe that a general Latent Class Analysis (LCA) model could potentially have three types of input data: Covariates, Distal Outcomes, and Indicators. However, I noticed that only two variables are allowed. Do you have any suggestions? If my understanding is correct, covariates and indicators are combined into an array used to estimate the parameters of the Measurement Model (MM). If we have distal outcomes (target labels), then the Structural Model (SM) is estimated again.

**Comment by yuanjames** [comment]
Any suggestions for distal outcomes and covariates? I see most of examples only use X, Y (i.e., indicators with distal outcomes, or indicators with covariates). How do I distiguish them?

**Comment by sachaMorin** [comment]
A model with distal outcomes is similar to regression analysis insofar as they can both give you a "supervised" model to predict Y from X (at least in theory, this is not currently implemented). The assumptions on the models are different however. In regression, your model is linear while here, the relationship between X and Y is mediated by some latent class Z. In clustering analysis, we are typically more interested in the latent class than predicting Y.

You are correct that in one-step estimation, there is some interaction between the measurement parameters and the structural parameters. This "leak" is what prompted the research around stepwise estimation methods to insulate the measurement estimation from the structural estimation.

**Comment by yuanjames** [comment]
Thanks for your explanation @sachaMorin ! Yes, I agree with you, but just to share, regression models could be non-linear, for example, neural networks. If we follow the Stepwise, I thought that latent classes are fixed when MM is estimated. Then, SM always plays an 'approximator' to do either distal outcomes analysis or covariate analysis, between latent classess and external variables.

**Comment by sachaMorin** [comment]
Closing. Feel free to reopen if you have other questions!
