### ISSUE TITLE
Max LL and Average LL

### ISSUE THREAD

**Issue by mohrezazali** [Labo-Lacourse/stepmix#55]
Hello. Something just grabbed my attention. My model's log_likeligood in each and every iteration was around 70,000 but at the end the average LL was only 3.9676. Can anybody explain how the Average was calculated?

<img width="617" alt="Screenshot 2024-01-27 at 11 49 58 PM" src="https://github.com/Labo-Lacourse/stepmix/assets/157144591/a484a442-a9e4-4887-b5a3-a34a4d10dc0f">

**Comment by sachaMorin** [comment]
Average LL = LL/(number of observations)

3.96 is your average LL and around 70,000 is your LL.  Are you getting different numbers in the progress bar?

**Comment by sachaMorin** [comment]
@mohrezazali  did this answer your question?

**Comment by sachaMorin** [comment]
Closing. Feel free to reopen if needed!
