### ISSUE TITLE
ID Class Prediction

### ISSUE THREAD

**Issue by mohrezazali** [Labo-Lacourse/stepmix#56]
Hi, I need to do predict_class and I need all rows with the same ID get the same class. I have ID, X1, X2 and Y. Could you let me know how I can incorporate ID column in the a StepMix model to perform class assignments while taking ID into account? In FLEXMIX in R the following code worked perfectly, but I need to know I can reproduce the same results with StepMix:

`fmm4 <- stepFlexmix(.~0|id,k=4,nrep=3, model=list(FLXMR...
`

many rows have the same id, but I want to make sure all rows with the same id will be in the same class. 
Thanks

**Comment by mohrezazali** [comment]
Thanks for the explanation.

**Comment by sachaMorin** [comment]
Closing. Feel free to reopen if needed.
