### ISSUE TITLE
Custom Feature weights supported?

### ISSUE THREAD

**Issue by jaanisfehling** [Labo-Lacourse/stepmix#63]
Hi, is there any way to add custom weights to each individual feature (i.e. user-defined weighting strategy)?
I think for continuous features I can just multiply the weights with the feature values, but is there any way to do this with categorical features? Can I just change the code to multiply the weights after one-hot encoding, or does this mess up the computation later on?

**Comment by sachaMorin** [comment]
Feature weights are not supported at the moment. Sample weights are. I'm not sure I understand your suggested change.

A very rough way to achieve this is to duplicate your target feature in the input data (e.g., add another column with the same data). This will effectively increase the weight of that feature in all likelihood computations. This not super efficient of course, but if you have a relatively small dataset, it might be worth a try. I would avoid doing this with the `gaussian_full` model, however.

**Comment by jaanisfehling** [comment]
Imagine you want to cluster a dataset and know that a persons age is not as important (in clustering) as a persons gender. You could weigh the age feature 50% and the gender feature 100% (or more). Using something like for clustering k-means, I could multiply the age column by 0.5 in beforehand, after scaling.

**Comment by jaanisfehling** [comment]
I am not an expert in statistics, but if I understand correctly, [this paper](https://link.springer.com/article/10.1007/s10994-016-5575-7) suggests multiplying the feature weights for categorical variables to the log-likelihoods in the E-step.

**Comment by sachaMorin** [comment]
Scaling the feature works for k-means since it's distance based: scaling a normalized feature will increase it's weight in the Euclidean distance computation.

If you are willing to change the code then yes, you can can tweak the likelihood contributions of the different  features.

**Comment by jaanisfehling** [comment]
For anyone interested, this is how I changed the log likelihood calculations (take it with a grain of salt, I am a statistics noob):
- For Gaussian Emission Models (gaussian.py, line 353):
```
        for c in range(self.n_components):
            diff = X - self.parameters["means"][c].reshape(1, -1)
            diff = diff * self.weights

```
- For Multinoulli (categorical.py, line 306 or line 188)
```
        X = self.encode_features(X)

        X = X * self.weights

        is_observed = ~np.isnan(X)
```
- For Bernoulli (categorical.py, line 86 or line 22)
```
    def log_likelihood(self, X):
        X = X * self.weights

        is_observed = ~np.isnan(X)
```
